### ISSUE TITLE
Initializing schema from SDL breaks when using scalar in Input Objects

### ISSUE THREAD

**Issue by qonn** [pekkah/tanka-graphql#842]
Currently, this breaks on v2.0.0,

Stack trace:
```
 An unhandled exception has occurred while executing the request.
      Tanka.GraphQL.SchemaBuilding.SchemaBuilderException: Type Date is not known by the builder.
         at Tanka.GraphQL.SchemaBuilding.ConnectionBuilder.EnsureTypeKnown(IType type)
         at Tanka.GraphQL.SchemaBuilding.ConnectionBuilder.Include(InputObjectType owner, KeyValuePair`2 field)
         at Tanka.GraphQL.SchemaBuilding.ConnectionBuilder.Include(InputObjectType owner, IEnumerable`1 fields)
         at Tanka.GraphQL.Tools.MergeTool.<>c__DisplayClass5_0.<MergeInputType>b__0(ConnectionBuilder connect)
         at Tanka.GraphQL.SchemaBuilding.SchemaBuilder.Connections(Action`1 connections)
         at Tanka.GraphQL.Tools.MergeTool.MergeInputType(ISchema right, SchemaBuilder builder, InputObjectType rightType)
         at Tanka.GraphQL.Tools.MergeTool.Schema(SchemaBuilder target, ISchema right)
         at Tanka.GraphQL.Tools.MergeTool.Schemas(SchemaBuilder target, ISchema[] schemas)
         at Tanka.GraphQL.Tools.MergeSchemaBuilderExtensions.Merge(SchemaBuilder builder, ISchema[] schemas)
         at Tanka.GraphQL.Tools.SchemaTools.MakeExecutableSchemaWithIntrospection(SchemaBuilder builder, IResolverMap resolvers, ISubscriberMap subscribers, IReadOnlyDictionary`2 converters, IReadOnlyDictionary`2 directives)
         at tanka_arguments_bug_test.Schemas..ctor(IResolverService resolverService) in C:\tanka-test\Schemas.cs:line 18
--- the rest of the stack trace were omitted due to only showing things related to depency injection ---
```

SDL:

```graphql
scalar Date

input InputTest {
    timestamp: Date # <-- this breaks
}

type Query {
    getDate(date: Date): String 
}

type Mutation {
    addDate(date: Date, inputTest: InputTest): String
}

schema {
    query: Query
    mutation: Mutation
    subscription: Subscription
}
```

How to reproduce:
```
Just follow the project here https://github.com/pekkah/tanka-graphql/tree/master/dev/graphql.dev.chat.web and create a very basic custom scalar and start using it in any Input Object.
```

Tanka GraphQL Version:
```Nuget v2.0.0```

**Comment by qonn** [comment]
After some more investigation, It turns out that this only happen when calling `MakeExecutableSchemaWithIntrospection()`, so I guess it has something to do with how the `SchemaBuilder.Merge` work.
